### ISSUE TITLE
Current examples do not work

### ISSUE THREAD

**Issue by hoppfrosch** [evilC/AHK-CHID#1]
Either your description is not good enough - or I missed something: after cloning your repository and cloning WinStructs (git@github.com:ahkscript/WinStructs.git) (which is needed as prerequisite but thats not mentioned on your page), I tried to run your examples:
- _AHKHID_test.ahk_ opens up an empty dialogbox (only white content)
- _test_normal.ahk_ as well as _test_classed.ahk_ run into the same error

Error message: 

```
test classed.ahk

Error in #include file "d:\Dev\GIT\AHK\AHK-CHID\CHID.ahk":
Call to nonexistent function.

Specifically: AHKHID_NumIsShort(Flag) ? (AHKHID_NumIsSigned(Flag) ? "Short" : "UShort") : (AHKHID_NumIsSigned(Flag...

Line#
140: if (Size)  
140: {
146: VarSetCapacity(Data, Size)  
147: d := new  _Struct(Winstructs.RAWINPUTDEVICE)
148: MsgBox,"SIZE: " Size ", sizeof: " d.Size()
149: r := DllCall("GetRawInputData", "Uint", RawInput, "UInt", Command, "Ptr", &Data, "UInt*", Size, "Uint", SizeHeader )
150: Flag := 0
--->    152: t := AHKHID_NumIsShort(Flag) ? (AHKHID_NumIsSigned(Flag) ? "Short" : "UShort") : (AHKHID_NumIsSigned(Flag) ? "Int" : (Flag = 8 ? "Ptr" : "UInt"))
154: v := NumGet(Data, 16, t)
155: Return,v
157: }
157: Else
157: {
158: r := DllCall("GetRawInputData", "Uint", RawInput, "UInt", Command, "Ptr", 0, "UInt*", Size, "Uint", SizeHeader )
159: }

The program will exit.
```

---

**Comment by evilC** [comment]
Yeah, you just jumped the gun on me a little there, I have marked the classed stuff as not working for now.
CHID is very much [Work in Progress], and by no means ready for consumption.

For now, I have had to drop the class based stuff until I get a significant portion of it working - only then will I know how everything slots together, thus enabling me to write helper classes to simplify the process.

If you wish to see the current bleeding edge, check the "Test Normal" script.
Even this though is partly functional, debug messages etc.
