### ISSUE TITLE
Fn key

### ISSUE THREAD

**Issue by eugenesvk** [evilC/AHK-CHID#8]
Just a quick question — will this project allow remapping of dead keys (e.g. `Fn` key)? The original AHKHID doesn't capture these keys as they don't send any key codes. Understand that it's a likely no (especially give that the project scope is joysticks at the moment ;)), but wanted to confirm as that's the last thing left that I can't remap on my keyboard in Windows.
Thank you

**Comment by evilC** [comment]
If AHKHID does not recognize the key, CHID also would not.
Also, there is unlikely to be any development on CHID for quite some time, as I have another project sucking all my time for the moment.

**Comment by eugenesvk** [comment]
Ok, understood. Thanks for your response. Whenever you return to this project or anything else AHK-related, please keep the `Fn` key in mind, the last bastion AHK hasn't managed to take, maybe you'll find a way!
